version: '3.5'

services:
  postgres:
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.16
  nats-streaming:
    image: nats-streaming
    restart: "always"
    ports:
      - "4222:4222"
      - "8222:8222"
